#!/usr/bin/env bash

set -euo pipefail

function log() {
    echo "[$(date -Iseconds)] $*"
} 1>&2

function github_api() {
    local url="$1"
    shift
    curl -fsSL \
         -H "Authorization: Bearer $CREATE_PR_TOKEN" \
         -H "Accept: application/json" \
         "$@" "https://api.github.com/$url"
}

function pr_exists() {
    local repo="$1"
    local branch="$2"
    local PR_COUNT=
    local PRs=

    log "Checking for existing PR for branch $branch"
    PRs="$(github_api "search/issues?q=repo:${repo}%20is:open%20is:pr%20label:%22${branch}%22" | jq -e '[.items[] | .number]')"

    PR_COUNT="$(echo "$PRs" | jq '. | length')"
    if [ "$PR_COUNT" -gt 0 ]; then
        printf "%s" "$(echo "$PRs" | jq -r '. | max')"
        return 0
    else
        return 1
    fi
}

function branch_exists() {
    local repo="$1"
    local branch="$2"
    log "Checking for existing branch $branch"
    if github_api "repos/${repo}/branches/${branch}" >/dev/null; then
        return 0
    else
        return 1
    fi
}


function main() {
    local title="$1"
    local description="$2"
    shift 2
    local pr_id=

    log "Checking for changes"

    git diff | cat

    git_changes="$(git status --porcelain -- "$@" || true)"

    if [ -n "$git_changes" ]; then
        log "Changes found; committing and pushing to $UPDATE_BRANCH"

        git add "$@"

        git commit --author "$AUTHOR" -m "$title"

        git push --force-with-lease -u origin "$UPDATE_BRANCH"
    fi

    local full_description=
    if [ -n "$description" ]; then
        full_description="$(printf "%s\n\nChanges generated by [GitHub Actions build](%s)" "$description" "${BUILD_URL}")"
    else
        full_description="$(printf "Changes generated by [GitHub Actions build](%s)" "${BUILD_URL}")"
    fi

    if pr_id="$(pr_exists "$GITHUB_REPOSITORY" "$UPDATE_BRANCH")"; then
        log "PR already exists"

        local pr_update_body=
        pr_update_body="$(jq -ne --arg body "$full_description" --arg title "$title" '{title: $title, body: $body}')"

        github_api \
           "repos/$GITHUB_REPOSITORY/pulls/${pr_id}" \
           -X PATCH \
           -H "Content-Type: application/json" \
           -d "$pr_update_body"

        exit 0
    fi

    if [ -n "$git_changes" ] || branch_exists "$GITHUB_REPOSITORY" "$UPDATE_BRANCH"; then
        log "Found pushed branch; creating PR"

        local pr_create_body=
        pr_create_body="$(
          jq -ne --argjson label_id "$label_id" --arg head "$UPDATE_BRANCH" --arg title "$title" --arg body "$full_description" \
          '{"assignee":"sjagoe","base":"main","head":$head, "title": $title, "body": $body, "labels": [$label_id]}'
        )"

        local created_pr=
        created_pr="$(github_api \
           "repos/$GITHUB_REPOSITORY/pulls" \
           -X POST \
           -H "Content-Type: application/json" \
           -d "$pr_create_body")"

        local pr_number=
        pr_number="$(echo "$created_pr" | jq -er '.number')"

        local label_data=
        label_data="$(jq -en --arg label "$UPDATE_BRANCH" '{labels: [$label]}')"
        github_api \
            "/repos/$GITHUB_REPOSITOR/issues/${pr_number}/labels" \
            -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2026-03-10" \
            -d "$label_data"
    fi
}


{
    main "$@"
}
