name: Build kernels

on:
  workflow_dispatch:

jobs:
  matrix:
    name: Generate matrix
    runs-on: [nix-flake-check, x86_64-linux]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Build matrix
        id: matrix
        run: |
          builds="$(nix eval --json .#ci.build)"
          separator="matrix-$RANDOM"
          {
            echo "matrix<<$separator"
            echo "$builds" | jq -e .
            echo "$separator"
          } >> "$FORGEJO_OUTPUT"
          cat "$FORGEJO_OUTPUT"

  build:
    name: Build kernel
    needs: matrix
    strategy:
      matrix:
        build: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: [nix-build, x86_64-linux]
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Build
        id: build
        env:
          BUILD: ${{ matrix.build }}
        run: |
          OUTPUT_NAMES="$(nix eval --json ".#${BUILD}.outputs" | jq -r '.[]')"
          mapfile -t OUTPUTS <<<"$OUTPUT_NAMES"
          TARGETS=()
          for output in "${OUTPUTS[@]}"; do
            TARGETS=(
              "${TARGETS[@]}"
              ".#${BUILD}.${output}"
            )
          done
          echo "Building ${TARGETS[*]}"
          BUILDS="$(nix build "${TARGETS[@]}" --print-out-paths --print-build-logs)"

          echo "$BUILDS"

          separator="builds-$RANDOM"
          {
            echo "builds<<$separator"
            echo "$BUILDS"
            echo "$separator"
          } >> "$FORGEJO_OUTPUT"
          cat "$FORGEJO_OUTPUT"

      - name: Push packages to cache
        env:
          BUILDS: ${{ steps.build.outputs.builds }}
        run: |
          mapfile -t BUILD_PATHS <<<"$BUILDS"
          for item in "${BUILD_PATHS[@]}"; do
            echo "Caching $item"
          done
