name: Build kernels

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  matrix:
    name: Generate matrix
    runs-on: [nix-flake-check, x86_64-linux]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Build matrix
        id: matrix
        run: |
          builds="$(nix eval --json .#ci.build)"
          separator="matrix-$RANDOM"
          {
            echo "matrix<<$separator"
            echo "$builds" | jq -e .
            echo "$separator"
          } >> "$FORGEJO_OUTPUT"
          cat "$FORGEJO_OUTPUT"

  build:
    name: Build kernel
    needs: matrix
    strategy:
      matrix:
        build: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: [nix-build, x86_64-linux]
    steps:
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4

      - name: Build and cache
        uses: https://git.jagoe.eu/actions/build@v1.0.2
        with:
          attic-cache-key: ${{ secrets.ATTIC_CACHE_KEY }}
          build-target: ".#${{ matrix.build }}"
          github-token: ${{ secrets.GH_APP_AUTH_TOKEN }}
          deploy-key-content: ${{ secrets.GIT_PRIVATE_READ_KEY }}
