name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */3 * * *"

jobs:
  update-kernels:
    name: Update kernels
    runs-on: nix-update
    env:
      UPDATE_BRANCH: ci/update/kernels
    steps:
      - name: Determine base
        id: base
        shell: bash
        run: |
          {
              if [[ "$FORGEJO_HEAD_REF" == "" ]]; then
                  echo "ref=$FORGEJO_REF_NAME"
              else
                  echo "ref=$FORGEJO_HEAD_REF"
              fi
          } >> "$FORGEJO_OUTPUT"
      - name: Checkout
        uses: https://data.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.base.outputs.ref }}
          token: ${{ secrets.CREATE_PR_TOKEN }}

      - name: Configure nix
        id: configure-nix
        uses: https://git.jagoe.eu/actions/configure-nix@v1.0.0
        with:
          github-token: ${{ secrets.GH_APP_AUTH_TOKEN }}

      - name: Prepare
        id: prepare
        uses: https://git.jagoe.eu/actions/prepare@v1.0.0
        with:
          update-branch: ${{ env.UPDATE_BRANCH }}
          base-ref: ${{ steps.base.outputs.ref }}

      - name: Update kernels
        id: update
        env:
          GIT_REF: ${{ steps.base.outputs.ref }}
          NIX_PATH: nixpkgs=${{ steps.prepare.outputs.nixpkgs }}
        run: |
          bash ./update-kernels.sh

      - name: Pull-request
        uses: https://git.jagoe.eu/actions/pull-request@v1.0.0
        with:
          update-branch: ${{ env.UPDATE_BRANCH }}
          commit-message: "Add kernel hashes"
          files: |
            kernels.json
          forgejo-token: ${{ secrets.CREATE_PR_TOKEN }}
