name: Build and cache nix artefacts
description: >
  Run a build and cache the result
inputs:
  pr-create-app-client-id:
    description: Client ID for the create-pr GitHub app
    required: true
  pr-create-app-private-key:
    description: Private Key for the create-pr GitHub app
    required: true
  update-branch-name:
    description: Branch name for the PR created by update
    required: true
  pull-request-base:
    description: Base ref for the created pull request
    required: true

runs:
  using: composite
  steps:
    - name: Create app token
      id: app-token
      uses: actions/create-github-app-token@v3
      with:
        client-id: ${{ inputs.pr-create-app-client-id }}
        private-key: ${{ inputs.pr-create-app-private-key }}

    - name: Get GitHub App User ID
      id: get-user-id
      env:
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      run: |
        echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Checkout update branch
      shell: bash
      env:
        REF: ${{ inputs.pull-request-base }}
        UPDATE_BRANCH: ${{ inputs.update-branch-name }}
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        USER_ID: ${{ steps.get-user-id.outputs.user-id }}
      run: |
        git config user.name "${APP_SLUG}[bot]"
        git config user.email "${USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
        git switch --create "$UPDATE_BRANCH" --track "origin/$UPDATE_BRANCH" ||
            git switch --create "$UPDATE_BRANCH"
        if ! git rebase "origin/$REF"; then
            git rebase --abort
            git reset --hard "origin/$REF"
        fi
