name: Build kernels

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build matrix
        id: matrix
        run: |
          echo "Store paths to build"
          nix eval --json .#packages | jq .
          echo "===="
          builds="$(nix eval --json .#ci.build)"
          separator="matrix-$RANDOM"
          {
            echo "matrix<<$separator"
            echo "$builds" | jq -e .
            echo "$separator"
          } >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

  build:
    name: Build kernel
    needs: matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Clean disk
        run: |
          df -h
          cat <<'EOF' > removepatterns
          ^ant.*
          ^apache2$
          ^autoconf$
          ^automake$
          ^bison$
          ^build-essential$
          ^buildah$
          ^gortran.*
          ^clang.*
          ^firefox$
          ^flex$
          ^g++.*
          ^gcc$
          ^google-chrome-stable$
          ^google-cloud-cli$
          ^kubectl$
          ^lldb.*
          ^microsoft-edge-stable$
          ^mysql.*
          ^nginx$
          ^packages-microsoft-prod$
          ^php.*
          ^postgresql.*
          ^powershell$
          ^skopeo$
          ^temurin.*
          EOF

          mapfile -t REMOVE < <(apt-mark showmanual | grep --file removepatterns)
          sudo apt-get remove --purge --autoremove "${REMOVE[@]}"

          sudo rm -rf /usr/local/julia1* /opt/hostedtoolcache/Py{thon,Py} /opt/hostedtoolcache/go /usr/local/lib/android /usr/share/dotnet /usr/share/swift /usr/local/share/powershell || true

          df -h

      - name: Checkout
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:${{ matrix.nixos-release }}

      - uses: cachix/cachix-action@v17
        with:
          name: nixos-kernels
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build
        env:
          BUILD: ${{ matrix.build }}
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_METADATA_TOKEN }}'
        run: |
          set -x
          BUILD_TARGETS="$(nix eval --json "${BUILD}.outputs" | jq -er --arg target "$BUILD" 'foreach .[] as $output (null; "\($target).\($output)")')"
          OPTIONS=(
            --no-link
            --print-out-paths
            --print-build-logs
          )
          mapfile -t TARGETS <<< "$BUILD_TARGETS"
          declare -a FINAL_TARGETS

          for target in "${TARGETS[@]}"; do
            store_path="$(nix eval --json "$target" | jq -er . | sed 's/\//%2F/g')"
            cachix_resp="$(curl -fsSL \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $CACHIX_AUTH_TOKEN" \
              "https://cachix.org/api/v1/cache/nixos-kernels/search/${store_path}")"
            exists="$(echo "$cachix_resp" | jq -er '(. | length) > 0')"
            if [[ "$exists" == "true" ]]; then
              echo "Skipping build of already-cached $target"
            else
              FINAL_TARGETS=("${FINAL_TARGETS[@]}" "$target")
            fi
          done

          if [ "${#FINAL_TARGETS[@]}" -eq 0 ]; then
            echo "Nothing to do"
            exit 0
          fi

          echo "Building targets ${FINAL_TARGETS[*]}"
          nix build "${FINAL_TARGETS[@]}" "${OPTIONS[@]}"
