name: Build kernels

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - README.md
      - .github/workflows/update.yml
      - .github/scripts/create-pr.sh
      - .github/scripts/generate-readme.sh
  push:
    branches: [main]
    paths-ignore:
      - README.md
      - .github/workflows/update.yml
      - .github/scripts/create-pr.sh
      - .github/scripts/generate-readme.sh

jobs:
  matrix:
    name: Generate matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build matrix
        id: matrix
        run: |
          bash .github/scripts/build-matrix.sh

  build:
    name: Build kernel
    needs: matrix
    strategy:
      matrix:
        include: ${{ fromJson(needs.matrix.outputs.matrix) }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Clean disk
        uses: sjagoe/avrea-disk-space-action@v1.0.2

      - name: Checkout
        uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:${{ matrix.nixos-release }}

      - uses: cachix/cachix-action@v17
        with:
          name: nixos-kernels
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build
        env:
          BUILD: ${{ matrix.build }}
          CACHIX_AUTH_TOKEN: '${{ secrets.CACHIX_METADATA_TOKEN }}'
        run: |
          BUILD_TARGETS="$(nix eval --json "${BUILD}.outputs" | jq -er --arg target "$BUILD" 'foreach .[] as $output (null; "\($target).\($output)")')"
          OPTIONS=(
            --no-link
            --print-out-paths
            --print-build-logs
          )
          mapfile -t TARGETS <<< "$BUILD_TARGETS"
          declare -a FINAL_TARGETS

          for target in "${TARGETS[@]}"; do
            store_path="$(nix eval --json "$target" | jq -er . | sed 's/\//%2F/g')"
            cachix_resp="$(curl -fsSL \
              -H "Accept: application/json" \
              -H "Authorization: Bearer $CACHIX_AUTH_TOKEN" \
              "https://cachix.org/api/v1/cache/nixos-kernels/search/${store_path}")"
            exists="$(echo "$cachix_resp" | jq -r '(. | length) > 0')"
            if [[ "$exists" == "true" ]]; then
              echo "Skipping build of already-cached $target"
              echo "$store_path is already in cache"
            else
              FINAL_TARGETS=("${FINAL_TARGETS[@]}" "$target")
            fi
          done

          if [ "${#FINAL_TARGETS[@]}" -eq 0 ]; then
            echo "Nothing to do"
            exit 0
          fi

          echo "Building targets ${FINAL_TARGETS[*]}"
          nix build "${FINAL_TARGETS[@]}" "${OPTIONS[@]}"

  build-completed:
    name: Build completed
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Finalize overall build status status
        env:
          STATE: ${{ needs.build.result }}
        run: |
          [[ "$STATE" == "success" ]]
