name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */3 * * *"

jobs:
  update-kernels:
    name: Update kernels
    runs-on: ubuntu-latest
    env:
      UPDATE_BRANCH: ci/update/kernels
    steps:
      - name: Create app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.PR_CREATE_APP_CLIENT_ID }}
          private-key: ${{ secrets.PR_CREATE_APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"

      - name: Determine base
        id: base
        shell: bash
        run: |
          {
              if [[ "$GITHUB_HEAD_REF" == "" ]]; then
                  echo "ref=$GITHUB_REF_NAME"
              else
                  echo "ref=$GITHUB_HEAD_REF"
              fi
          } >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ steps.base.outputs.ref }}
          token: ${{ steps.app-token.outputs.token }}

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Checkout update branch
        shell: bash
        env:
          REF: ${{ steps.base.outputs.ref }}
          UPDATE_BRANCH: ${{ env.UPDATE_BRANCH }}
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          USER_ID: ${{ steps.get-user-id.outputs.user-id }}
        run: |
          git config user.name "${APP_SLUG}[bot]"
          git config user.email "${USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
          git switch --create "$UPDATE_BRANCH" --track "origin/$UPDATE_BRANCH" ||
              git switch --create "$UPDATE_BRANCH"
          if ! git rebase "origin/$REF"; then
              git rebase --abort
              git reset --hard "origin/$REF"
          fi

      - name: Update kernels
        id: update
        env:
          GIT_REF: ${{ steps.base.outputs.ref }}
        run: |
          bash ./update-kernels.sh

      - name: Push and create PR
        shell: bash
        env:
          BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          AUTHOR: "nixos-kernels-robot <nixos-kernels-robot@fake-email>"
          UPDATE_BRANCH: ${{ env.UPDATE_BRANCH }}
          MESSAGE: "Update kernel hashes"
          DESCRIPTION: ""
          FILES_LIST: |
            kernels.json
          CREATE_PR_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          mapfile -t FILES < <(echo "$FILES_LIST" | grep -v '^$')
          for filename in "${FILES[@]}"; do
            echo "$filename"
          done
          bash ".github/scripts/create-pr.sh" "$MESSAGE" "$DESCRIPTION" "${FILES[@]}"
